language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis 
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: onguntoglu
  password:
    secure: rejZTI4mVbwC6YvuQ2OWHo3qvLWSuSbfeQEVMfgOjWPERsOg4SWt2F1GMLakYXmVLjtP97chGfnW0Sf/02jKW8J0gaLmTgqSMECqNPgDMmOT5vneTs3lFjn8XFmjLgAy4zFGq0qt5TfMkyDCGalJQBmJiqTTXylQONlebY+v+CYnpCHFL6GVzK4Sum38sXTbdwdR9U4pOIz0E0obdBCPFmrdcgcfi+O4gZEFweM4MYaJKYUaXUiBTo/IOTlogFMw85HBchCXwJ7MDoYmAYjHWSHvCEZoIUD60X6eS+rnrXuNaTKmFhluQ8L7mE+A3HAfEdaifRdweeHTwLpg5aDCo7W971h04DzdNaabdAaC1dxPaogiJbKg3srg85Jo1dX2mSUeSRPhXia7f83LddfqOTwVSHQ8ItBB3LuEBUV+yLTNW18To8RC6c588a55pRDB7okR/EDYx5MCuI2zPrR6J0QGM6k2qkZ+ZjpGwiILoXOpjI4wxvLZ3aiLsVJP61UXQUtdHSlwuqMu5OGIq9pU/BQ2azqmkmLtA5/mxqMo97wU0pNuLW5iRKbZXdNbvZKdHigEC1oxRwaBipo+qBgOldWLvuUJDCfAEX4pcb6xOmwvs5Rr6maH6yR84TAU88TQecKE0clhP75+p+ZJ+fLQPRrdj110YG97NzINfE/h/oU=
  on:
    tags: true
    repo: onguntoglu/pyadrc
    python: 3.8

after_success:
  - bash <(curl -s https://codecov.io/bash) -v
  